[package]
name = "gtk-glium"
version = "0.1.0"
authors = ["Ponas <mykolas.peteraitis@gmail.com>"]
edition = "2018"

[dependencies]
gtk = { version = "0.9.2", features=["v3_16"] }
gio = "*"
glib = "*"
glium = { git = "https://github.com/glium/glium.git" }
gl_loader = "0.1.2"